### ISSUE TITLE
Key definitions update

### ISSUE THREAD

**Issue by usaoc** [dalanicolai/pdf-continuous-scroll-mode.el#19] opened 2022-02-21 05:26 UTC
Some key definitions in `pdf-view-mode-map` are no longer valid.  For example, `M-g (M-)g` is defined to `pdf-cscroll-view-goto-page`, which is now a void function.

**Comment by dalanicolai** [comment] 2022-02-21 15:37
Thank you for reporting the issue. I have been working on a version that could be merged into pdf-tools. However, finding the cause of bugs takes a lot of time, which I do not have available (I will probably create a kickstarter, or something like that, to ask the community to help me finish the package). Unfortunately, I will probably not be fixing issues for the current package. The package overwrites the function `pdf-view-goto-page`, I guess that function works for jumping to pages, in which case it should probably be easy to remap the current keybinding to that function.

**Comment by dalanicolai** [comment] 2022-05-05 12:54
Closing the issue for archiving this repo. A better implementation is available at https://github.com/dalanicolai/image-roll.el

**Closed as completed by dalanicolai** 2022-05-05 12:54 UTC
